# Bosnian cities and municipalities
BOSNIAN_CITIES = [
    # Federation of Bosnia and Herzegovina - Major cities
    "Sarajevo",
    "Banja Luka",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Bihać",
    "Brčko",
    "Prijedor",
    "Trebinje",
    "Bijeljina",
    "Cazin",
    "Visoko",
    "Goražde",
    "Gračanica",
    "Gradačac",
    "Bosanska Krupa",
    "Kiseljak",
    "Lukavac",
    "Živinice",
    "Busovača",
    "Bugojno",
    "Jajce",
    "Travnik",
    "Livno",
    "Konjic",
    "Čapljina",
    "Orašje",
    "Zavidovići",
    "Zvornik",
    "Doboj",
    "Srebrenik",
    "Kakanj",
    "Sanski Most",
    "Tešanj",
    "Visoko",
    "Vareš",
    "Maglaj",
    "Odžak",
    "Kalesija",
    "Kladanj",
    "Sapna",
    "Vlasenica",
    "Srebrenica",
    "Bratunac",
    "Milići",
    "Šekovići",
    "Han Pijesak",
    "Rogatica",
    "Višegrad",
    "Čajniče",
    "Rudo",
    "Foča",
    "Kalinovik",
    "Nevesinje",
    "Gacko",
    "Bileća",
    "Ljubinje",
    "Berkovići",
    "Stolac",
    "Čitluk",
    "Ljubuški",
    "Posušje",
    "Grude",
    "Široki Brijeg",
    "Tomislavgrad",
    "Kupres",
    "Glamoč",
    "Drvar",
    "Bosansko Grahovo",
    "Bosanski Petrovac",
    "Ključ",
    "Bosanska Dubica",
    "Bosanska Gradiška",
    "Laktaši",
    "Prnjavor",
    "Derventa",
    "Modriča",
    "Šamac",
    "Lopare",
    "Ugljevik",
    "Čelinac",
    "Kotor Varoš",
    "Kneževo",
    "Mrkonjić Grad",
    "Ribnik",
    "Oštra Luka",
    "Krupa na Uni",
    "Novi Grad",
    "Kostajnica",
    "Kozarska Dubica",
    "Gradiška",
    "Srbac",
    "Pelagićevo",
    "Donji Žabar",
    "Teslić",
    "Petrovo",
    "Modriča",
    "Vukosavlje",
    "Olovo",
    "Vareš",
    "Breza",
    "Ilijaš",
    "Hadžići",
    "Ilidža",
    "Novi Grad Sarajevo",
    "Novo Sarajevo",
    "Centar Sarajevo",
    "Stari Grad Sarajevo",
    "Vogošća",
    "Trnovo",
    "Pale",
    "Sokolac",
    "Ustiprača",
    "Ustikolina",
    "Kalesija",
    "Osmaci",
    "Teočak",
    "Lopare",
    "Čelić",
    "Lukavac",
    "Banovići",
    "Zavidovići",
    "Žepče",
    "Usora",
    "Doboj Istok",
    "Doboj Jug",
    "Vares",
    "Breza",
    "Kreševo",
    "Fojnica",
    "Novi Travnik",
    "Vitez",
    "Prozor-Rama",
    "Jablanica",
    "Konjic",
    "Gornji Vakuf-Uskoplje",
    "Donji Vakuf",
    "Bugojno",
    "Kupres",
    "Livno",
    "Tomislavgrad",
    "Posušje",
    "Grude",
    "Široki Brijeg",
    "Mostar",
    "Čitluk",
    "Stolac",
    "Čapljina",
    "Neum",
    "Ravno",
    "Trebinje",
    "Bileća",
    "Ljubinje",
    "Nevesinje",
    "Gacko",
    "Kalinovik",
    "Foča",
    "Čajniče",
    "Rudo",
    "Višegrad",
    "Rogatica",
    "Sokolac",
    "Han Pijesak",
    "Vlasenica",
    "Milići",
    "Srebrenica",
    "Bratunac",
    "Zvornik",
]

# Remove duplicates and sort
BOSNIAN_CITIES = sorted(list(set(BOSNIAN_CITIES)))
