"""Add search_logs table for search quality tracking

Revision ID: 12581959c664
Revises: 25170e33c754
Create Date: 2025-12-09 09:43:51.728916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12581959c664'
down_revision: Union[str, None] = '25170e33c754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('total_before_filter', sa.Integer(), nullable=True),
    sa.Column('results_detail', sa.JSON(), nullable=True),
    sa.Column('parsed_query', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_search_logs_created_at', 'search_logs', ['created_at'], unique=False)
    op.create_index('idx_search_logs_query', 'search_logs', ['query'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_search_logs_query', table_name='search_logs')
    op.drop_index('idx_search_logs_created_at', table_name='search_logs')
    op.drop_table('search_logs')
    # ### end Alembic commands ###
