"""Add api_usage_logs table for tracking LLM API usage

Revision ID: 194ab4270a98
Revises: 47be96233c46
Create Date: 2026-01-29 09:25:11.548749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '194ab4270a98'
down_revision: Union[str, None] = '47be96233c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_cents', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_created_at'), 'api_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_feature'), 'api_usage_logs', ['feature'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_model'), 'api_usage_logs', ['model'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_provider'), 'api_usage_logs', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_usage_logs_provider'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_model'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_feature'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_created_at'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
