"""Add product matching fields and product_matches table

Revision ID: 1d0c5abffcb5
Revises: 350c8eea97b9
Create Date: 2025-12-16 15:08:53.978311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0c5abffcb5'
down_revision: Union[str, None] = '350c8eea97b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_a_id', sa.Integer(), nullable=False),
    sa.Column('product_b_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_a_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_b_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_a_id', 'product_b_id', 'match_type', name='uq_product_match')
    )
    op.create_index('idx_product_matches_product_a', 'product_matches', ['product_a_id'], unique=False)
    op.create_index('idx_product_matches_product_b', 'product_matches', ['product_b_id'], unique=False)
    op.create_index('idx_product_matches_type', 'product_matches', ['match_type'], unique=False)
    op.add_column('products', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('products', sa.Column('product_type', sa.String(), nullable=True))
    op.add_column('products', sa.Column('size_value', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('size_unit', sa.String(), nullable=True))
    op.add_column('products', sa.Column('variant', sa.String(), nullable=True))
    op.add_column('products', sa.Column('match_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_match_key'), 'products', ['match_key'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_match_key'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_column('products', 'match_key')
    op.drop_column('products', 'variant')
    op.drop_column('products', 'size_unit')
    op.drop_column('products', 'size_value')
    op.drop_column('products', 'product_type')
    op.drop_column('products', 'brand')
    op.drop_index('idx_product_matches_type', table_name='product_matches')
    op.drop_index('idx_product_matches_product_b', table_name='product_matches')
    op.drop_index('idx_product_matches_product_a', table_name='product_matches')
    op.drop_table('product_matches')
    # ### end Alembic commands ###
