"""Add cropped_image_url to receipts table

Revision ID: 218b94fd3b74
Revises: ae81d089d3bb
Create Date: 2026-01-29 18:18:51.558011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '218b94fd3b74'
down_revision: Union[str, None] = 'ae81d089d3bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('cropped_image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'cropped_image_url')
    # ### end Alembic commands ###
