"""Add email_events table for SendGrid tracking

Revision ID: 2ab2cc41678f
Revises: f476c2810ecd
Create Date: 2025-12-21 00:52:31.407239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ab2cc41678f'
down_revision: Union[str, None] = 'f476c2810ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('sg_message_id', sa.String(), nullable=True),
    sa.Column('sg_event_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sg_event_id')
    )
    op.create_index('idx_email_events_email', 'email_events', ['email'], unique=False)
    op.create_index('idx_email_events_timestamp', 'email_events', ['timestamp'], unique=False)
    op.create_index('idx_email_events_type', 'email_events', ['event_type'], unique=False)
    op.create_index('idx_email_events_user', 'email_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_events_email'), 'email_events', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_events_email'), table_name='email_events')
    op.drop_index('idx_email_events_user', table_name='email_events')
    op.drop_index('idx_email_events_type', table_name='email_events')
    op.drop_index('idx_email_events_timestamp', table_name='email_events')
    op.drop_index('idx_email_events_email', table_name='email_events')
    op.drop_table('email_events')
    # ### end Alembic commands ###
