"""Add user_daily_visits table

Revision ID: 2b7ac9955063
Revises: 036c24c43da0
Create Date: 2025-12-14 19:06:02.070291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7ac9955063'
down_revision: Union[str, None] = '036c24c43da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_daily_visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('page_views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'visit_date', name='uq_user_daily_visit')
    )
    op.create_index('idx_user_daily_visits_date', 'user_daily_visits', ['visit_date'], unique=False)
    op.create_index('idx_user_daily_visits_user_date', 'user_daily_visits', ['user_id', 'visit_date'], unique=False)
    op.create_index('idx_user_daily_visits_user_id', 'user_daily_visits', ['user_id'], unique=False)
    op.drop_index('products_enriched_desc_trgm_idx', table_name='products', postgresql_using='gin')
    op.drop_index('products_title_trgm_idx', table_name='products', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('products_title_trgm_idx', 'products', [sa.text('lower(title::text)')], unique=False, postgresql_using='gin')
    op.create_index('products_enriched_desc_trgm_idx', 'products', [sa.text('lower(enriched_description)')], unique=False, postgresql_using='gin')
    op.drop_index('idx_user_daily_visits_user_id', table_name='user_daily_visits')
    op.drop_index('idx_user_daily_visits_user_date', table_name='user_daily_visits')
    op.drop_index('idx_user_daily_visits_date', table_name='user_daily_visits')
    op.drop_table('user_daily_visits')
    # ### end Alembic commands ###
