"""Add user_product_images table

Revision ID: 2cde57625f0f
Revises: 64b7a0924088
Create Date: 2025-12-27 16:24:18.715167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cde57625f0f'
down_revision: Union[str, None] = '64b7a0924088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('extracted_name', sa.String(), nullable=True),
    sa.Column('extracted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('matched_product_id', sa.Integer(), nullable=True),
    sa.Column('user_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_product_images_status', 'user_product_images', ['status'], unique=False)
    op.create_index('idx_user_product_images_user', 'user_product_images', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_product_images_user', table_name='user_product_images')
    op.drop_index('idx_user_product_images_status', table_name='user_product_images')
    op.drop_table('user_product_images')
    # ### end Alembic commands ###
