"""Add device info columns to user_logins

Revision ID: 31ea1132e7f2
Revises: bdc61d3418b4
Create Date: 2025-12-10 08:00:13.392467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ea1132e7f2'
down_revision: Union[str, None] = 'bdc61d3418b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # DO NOT drop trgm indexes - they're needed for hybrid search
    # op.drop_index('products_enriched_desc_trgm_idx', table_name='products', postgresql_using='gin')
    # op.drop_index('products_title_trgm_idx', table_name='products', postgresql_using='gin')
    op.create_index(op.f('ix_search_logs_query'), 'search_logs', ['query'], unique=False)
    op.add_column('user_logins', sa.Column('device_type', sa.String(length=20), nullable=True))
    op.add_column('user_logins', sa.Column('os_name', sa.String(length=50), nullable=True))
    op.add_column('user_logins', sa.Column('browser_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_logins', 'browser_name')
    op.drop_column('user_logins', 'os_name')
    op.drop_column('user_logins', 'device_type')
    op.drop_index(op.f('ix_search_logs_query'), table_name='search_logs')
    # DO NOT recreate trgm indexes in downgrade - they already exist
    # op.create_index('products_title_trgm_idx', 'products', [sa.text('lower(title::text)')], unique=False, postgresql_using='gin')
    # op.create_index('products_enriched_desc_trgm_idx', 'products', [sa.text('lower(enriched_description)')], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
