"""Add welcome_guide_seen flag to users

Revision ID: 350c8eea97b9
Revises: bf636465c49a
Create Date: 2025-12-15 23:07:55.514800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350c8eea97b9'
down_revision: Union[str, None] = 'bf636465c49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('welcome_guide_seen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'welcome_guide_seen')
    # ### end Alembic commands ###
