"""Add preferences_hash to user_product_scans

Revision ID: 371e2e8c9bfc
Revises: c97a60f96378
Create Date: 2025-12-19 07:23:55.590204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371e2e8c9bfc'
down_revision: Union[str, None] = 'c97a60f96378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_product_scans', sa.Column('preferences_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_product_scans', 'preferences_hash')
    # ### end Alembic commands ###
