"""Add duplicate_of_id and scheduled_delete_at to receipts

Revision ID: 47be96233c46
Revises: dbd1b1b035d4
Create Date: 2026-01-25 18:58:38.040446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47be96233c46'
down_revision: Union[str, None] = 'dbd1b1b035d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_auth_tokens_token_key', 'email_auth_tokens', type_='unique')
    op.create_index(op.f('ix_email_auth_tokens_token'), 'email_auth_tokens', ['token'], unique=True)
    op.drop_constraint('email_auth_tokens_user_id_fkey', 'email_auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'email_auth_tokens', 'users', ['user_id'], ['id'])
    op.drop_index('idx_products_discount_starts', table_name='products')
    op.add_column('receipts', sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
    op.add_column('receipts', sa.Column('scheduled_delete_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_receipts_scheduled_delete_at'), 'receipts', ['scheduled_delete_at'], unique=False)
    op.create_foreign_key(None, 'receipts', 'receipts', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_users_city_id', table_name='users')
    op.drop_index('idx_users_first_touch_source', table_name='users')
    op.create_index(op.f('ix_users_city_id'), 'users', ['city_id'], unique=False)
    op.drop_constraint('fk_users_city_id', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('fk_users_city_id', 'users', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_city_id'), table_name='users')
    op.create_index('idx_users_first_touch_source', 'users', ['first_touch_source'], unique=False)
    op.create_index('idx_users_city_id', 'users', ['city_id'], unique=False)
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_index(op.f('ix_receipts_scheduled_delete_at'), table_name='receipts')
    op.drop_column('receipts', 'scheduled_delete_at')
    op.drop_column('receipts', 'duplicate_of_id')
    op.create_index('idx_products_discount_starts', 'products', ['discount_starts'], unique=False)
    op.drop_constraint(None, 'email_auth_tokens', type_='foreignkey')
    op.create_foreign_key('email_auth_tokens_user_id_fkey', 'email_auth_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_email_auth_tokens_token'), table_name='email_auth_tokens')
    op.create_unique_constraint('email_auth_tokens_token_key', 'email_auth_tokens', ['token'])
    # ### end Alembic commands ###
