"""Add social_media_posts table

Revision ID: 64b7a0924088
Revises: c6842c8527d7
Create Date: 2025-12-26 18:14:23.820855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b7a0924088'
down_revision: Union[str, None] = 'c6842c8527d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('products_data', sa.JSON(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('facebook_post_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_social_posts_scheduled', 'social_media_posts', ['scheduled_time'], unique=False)
    op.create_index('idx_social_posts_status', 'social_media_posts', ['status'], unique=False)
    op.create_index(op.f('ix_social_media_posts_scheduled_time'), 'social_media_posts', ['scheduled_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_media_posts_scheduled_time'), table_name='social_media_posts')
    op.drop_index('idx_social_posts_status', table_name='social_media_posts')
    op.drop_index('idx_social_posts_scheduled', table_name='social_media_posts')
    op.drop_table('social_media_posts')
    # ### end Alembic commands ###
