"""Add ProductView table for impression tracking

Revision ID: 6632138fff92
Revises: 73d6602e629b
Create Date: 2025-12-31 12:47:34.974562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6632138fff92'
down_revision: Union[str, None] = '73d6602e629b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_views_created_at', 'product_views', ['created_at'], unique=False)
    op.create_index('idx_product_views_product_id', 'product_views', ['product_id'], unique=False)
    op.create_index('idx_product_views_product_user', 'product_views', ['product_id', 'user_id'], unique=False)
    op.create_index('idx_product_views_user_id', 'product_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_views_user_id', table_name='product_views')
    op.drop_index('idx_product_views_product_user', table_name='product_views')
    op.drop_index('idx_product_views_product_id', table_name='product_views')
    op.drop_index('idx_product_views_created_at', table_name='product_views')
    op.drop_table('product_views')
    # ### end Alembic commands ###
