"""Add JobRun and EmailNotification models

Revision ID: 67b507e1b4fd
Revises: 9500046c4d50
Create Date: 2025-12-24 11:14:47.095732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b507e1b4fd'
down_revision: Union[str, None] = '9500046c4d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('records_success', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_runs_name_started', 'job_runs', ['job_name', 'started_at'], unique=False)
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.create_table('email_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_notifications_type_sent', 'email_notifications', ['email_type', 'sent_at'], unique=False)
    op.create_index('idx_email_notifications_user_sent', 'email_notifications', ['user_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_email_notifications_email'), 'email_notifications', ['email'], unique=False)
    op.create_index(op.f('ix_email_notifications_email_type'), 'email_notifications', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_notifications_user_id'), 'email_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_notifications_user_id'), table_name='email_notifications')
    op.drop_index(op.f('ix_email_notifications_email_type'), table_name='email_notifications')
    op.drop_index(op.f('ix_email_notifications_email'), table_name='email_notifications')
    op.drop_index('idx_email_notifications_user_sent', table_name='email_notifications')
    op.drop_index('idx_email_notifications_type_sent', table_name='email_notifications')
    op.drop_table('email_notifications')
    op.drop_index(op.f('ix_job_runs_job_name'), table_name='job_runs')
    op.drop_index('idx_job_runs_name_started', table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
