"""Add camera button analytics table

Revision ID: 73d6602e629b
Revises: 2cde57625f0f
Create Date: 2025-12-28 23:11:43.385619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d6602e629b'
down_revision: Union[str, None] = '2cde57625f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_button_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('uploaded_image_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_image_id'], ['user_product_images.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_camera_analytics_action', 'camera_button_analytics', ['action'], unique=False)
    op.create_index('idx_camera_analytics_created', 'camera_button_analytics', ['created_at'], unique=False)
    op.create_index('idx_camera_analytics_session', 'camera_button_analytics', ['session_id'], unique=False)
    op.create_index('idx_camera_analytics_user', 'camera_button_analytics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_camera_analytics_user', table_name='camera_button_analytics')
    op.drop_index('idx_camera_analytics_session', table_name='camera_button_analytics')
    op.drop_index('idx_camera_analytics_created', table_name='camera_button_analytics')
    op.drop_index('idx_camera_analytics_action', table_name='camera_button_analytics')
    op.drop_table('camera_button_analytics')
    # ### end Alembic commands ###
