"""Add campaigns table and update business model

Revision ID: 9500046c4d50
Revises: e89fdecbf86f
Create Date: 2025-12-24 07:17:36.155940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9500046c4d50'
down_revision: Union[str, None] = 'e89fdecbf86f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_coupons', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaigns_active', 'campaigns', ['is_active'], unique=False)
    op.create_index('idx_campaigns_business', 'campaigns', ['business_id'], unique=False)
    op.add_column('businesses', sa.Column('max_campaigns_allowed', sa.Integer(), nullable=True))
    op.drop_column('businesses', 'max_coupons_allowed')
    op.add_column('coupons', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_index('idx_coupons_campaign', 'coupons', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'coupons', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_index('idx_coupons_campaign', table_name='coupons')
    op.drop_column('coupons', 'campaign_id')
    op.add_column('businesses', sa.Column('max_coupons_allowed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'max_campaigns_allowed')
    op.drop_index('idx_campaigns_business', table_name='campaigns')
    op.drop_index('idx_campaigns_active', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
