"""Add cropped_top_url and cropped_bottom_url to receipts

Revision ID: 96e2fc992d14
Revises: 218b94fd3b74
Create Date: 2026-01-29 21:22:29.078916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e2fc992d14'
down_revision: Union[str, None] = '218b94fd3b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('cropped_top_url', sa.String(length=500), nullable=True))
    op.add_column('receipts', sa.Column('cropped_bottom_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'cropped_bottom_url')
    op.drop_column('receipts', 'cropped_top_url')
    # ### end Alembic commands ###
