"""Add user activity tracking tables and last_login field

Revision ID: bdc61d3418b4
Revises: fc14aa07c34f
Create Date: 2025-12-09 21:41:18.072016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc61d3418b4'
down_revision: Union[str, None] = 'fc14aa07c34f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('page', sa.String(length=100), nullable=True),
    sa.Column('activity_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_activities_created_at', 'user_activities', ['created_at'], unique=False)
    op.create_index('idx_user_activities_type', 'user_activities', ['activity_type'], unique=False)
    op.create_index('idx_user_activities_user_id', 'user_activities', ['user_id'], unique=False)
    op.create_index('idx_user_activities_user_type', 'user_activities', ['user_id', 'activity_type'], unique=False)
    op.create_table('user_logins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('login_method', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_logins_created_at', 'user_logins', ['created_at'], unique=False)
    op.create_index('idx_user_logins_user_id', 'user_logins', ['user_id'], unique=False)
    # Keep trgm indexes - they are needed for hybrid search
    # op.drop_index('products_enriched_desc_trgm_idx', table_name='products', postgresql_using='gin')
    # op.drop_index('products_title_trgm_idx', table_name='products', postgresql_using='gin')
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    # Keep trgm indexes - they already exist
    # op.create_index('products_title_trgm_idx', 'products', [sa.text('lower(title::text)')], unique=False, postgresql_using='gin')
    # op.create_index('products_enriched_desc_trgm_idx', 'products', [sa.text('lower(enriched_description)')], unique=False, postgresql_using='gin')
    op.drop_index('idx_user_logins_user_id', table_name='user_logins')
    op.drop_index('idx_user_logins_created_at', table_name='user_logins')
    op.drop_table('user_logins')
    op.drop_index('idx_user_activities_user_type', table_name='user_activities')
    op.drop_index('idx_user_activities_user_id', table_name='user_activities')
    op.drop_index('idx_user_activities_type', table_name='user_activities')
    op.drop_index('idx_user_activities_created_at', table_name='user_activities')
    op.drop_table('user_activities')
    # ### end Alembic commands ###
