"""Add category_group to products

Revision ID: bf636465c49a
Revises: 2b7ac9955063
Create Date: 2025-12-14 20:07:51.793977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf636465c49a'
down_revision: Union[str, None] = '2b7ac9955063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category_group')
    # ### end Alembic commands ###
