"""Add CASCADE DELETE to all user foreign keys

Revision ID: c6842c8527d7
Revises: 67b507e1b4fd
Create Date: 2025-12-24 20:24:01.001657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6842c8527d7'
down_revision: Union[str, None] = '67b507e1b4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_invitations_redeemed_by_user_id_fkey', 'business_invitations', type_='foreignkey')
    op.drop_constraint('business_invitations_invited_by_user_id_fkey', 'business_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'business_invitations', 'users', ['invited_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'business_invitations', 'users', ['redeemed_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('business_memberships_user_id_fkey', 'business_memberships', type_='foreignkey')
    op.drop_constraint('business_memberships_business_id_fkey', 'business_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'business_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'business_memberships', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('campaigns_created_by_user_id_fkey', 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('coupons_created_by_user_id_fkey', 'coupons', type_='foreignkey')
    op.create_foreign_key(None, 'coupons', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('credit_transactions_user_id_fkey', 'credit_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'credit_transactions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('favorites_user_id_fkey', 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('flask_dance_oauth_user_id_fkey', 'flask_dance_oauth', type_='foreignkey')
    op.create_foreign_key(None, 'flask_dance_oauth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.drop_constraint('notifications_product_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('product_comments_user_id_fkey', 'product_comments', type_='foreignkey')
    op.create_foreign_key(None, 'product_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('product_votes_user_id_fkey', 'product_votes', type_='foreignkey')
    op.create_foreign_key(None, 'product_votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('referrals_referrer_code_fkey', 'referrals', type_='foreignkey')
    op.drop_constraint('referrals_referred_user_id_fkey', 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'users', ['referred_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'referrals', 'users', ['referrer_code'], ['referral_code'], ondelete='CASCADE')
    op.drop_constraint('shopping_list_items_list_id_fkey', 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key(None, 'shopping_list_items', 'shopping_lists', ['list_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('shopping_lists_user_id_fkey', 'shopping_lists', type_='foreignkey')
    op.create_foreign_key(None, 'shopping_lists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sms_outbox_list_id_fkey', 'sms_outbox', type_='foreignkey')
    op.drop_constraint('sms_outbox_user_id_fkey', 'sms_outbox', type_='foreignkey')
    op.create_foreign_key(None, 'sms_outbox', 'shopping_lists', ['list_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sms_outbox', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_activities_user_id_fkey', 'user_activities', type_='foreignkey')
    op.create_foreign_key(None, 'user_activities', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_coupons_user_id_fkey', 'user_coupons', type_='foreignkey')
    op.drop_constraint('user_coupons_coupon_id_fkey', 'user_coupons', type_='foreignkey')
    op.create_foreign_key(None, 'user_coupons', 'coupons', ['coupon_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_coupons', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_daily_visits_user_id_fkey', 'user_daily_visits', type_='foreignkey')
    op.create_foreign_key(None, 'user_daily_visits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_engagements_user_id_fkey', 'user_engagements', type_='foreignkey')
    op.create_foreign_key(None, 'user_engagements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_feedback_user_id_fkey', 'user_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'user_feedback', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('user_logins_user_id_fkey', 'user_logins', type_='foreignkey')
    op.create_foreign_key(None, 'user_logins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_searches_user_id_fkey', 'user_searches', type_='foreignkey')
    op.create_foreign_key(None, 'user_searches', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_searches', type_='foreignkey')
    op.create_foreign_key('user_searches_user_id_fkey', 'user_searches', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_logins', type_='foreignkey')
    op.create_foreign_key('user_logins_user_id_fkey', 'user_logins', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_feedback', type_='foreignkey')
    op.create_foreign_key('user_feedback_user_id_fkey', 'user_feedback', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_engagements', type_='foreignkey')
    op.create_foreign_key('user_engagements_user_id_fkey', 'user_engagements', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_daily_visits', type_='foreignkey')
    op.create_foreign_key('user_daily_visits_user_id_fkey', 'user_daily_visits', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_coupons', type_='foreignkey')
    op.drop_constraint(None, 'user_coupons', type_='foreignkey')
    op.create_foreign_key('user_coupons_coupon_id_fkey', 'user_coupons', 'coupons', ['coupon_id'], ['id'])
    op.create_foreign_key('user_coupons_user_id_fkey', 'user_coupons', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_activities', type_='foreignkey')
    op.create_foreign_key('user_activities_user_id_fkey', 'user_activities', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sms_outbox', type_='foreignkey')
    op.drop_constraint(None, 'sms_outbox', type_='foreignkey')
    op.create_foreign_key('sms_outbox_user_id_fkey', 'sms_outbox', 'users', ['user_id'], ['id'])
    op.create_foreign_key('sms_outbox_list_id_fkey', 'sms_outbox', 'shopping_lists', ['list_id'], ['id'])
    op.drop_constraint(None, 'shopping_lists', type_='foreignkey')
    op.create_foreign_key('shopping_lists_user_id_fkey', 'shopping_lists', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'shopping_list_items', type_='foreignkey')
    op.create_foreign_key('shopping_list_items_list_id_fkey', 'shopping_list_items', 'shopping_lists', ['list_id'], ['id'])
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key('referrals_referred_user_id_fkey', 'referrals', 'users', ['referred_user_id'], ['id'])
    op.create_foreign_key('referrals_referrer_code_fkey', 'referrals', 'users', ['referrer_code'], ['referral_code'])
    op.drop_constraint(None, 'product_votes', type_='foreignkey')
    op.create_foreign_key('product_votes_user_id_fkey', 'product_votes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'product_comments', type_='foreignkey')
    op.create_foreign_key('product_comments_user_id_fkey', 'product_comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_product_id_fkey', 'notifications', 'products', ['product_id'], ['id'])
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'flask_dance_oauth', type_='foreignkey')
    op.create_foreign_key('flask_dance_oauth_user_id_fkey', 'flask_dance_oauth', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key('favorites_user_id_fkey', 'favorites', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'credit_transactions', type_='foreignkey')
    op.create_foreign_key('credit_transactions_user_id_fkey', 'credit_transactions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.create_foreign_key('coupons_created_by_user_id_fkey', 'coupons', 'users', ['created_by_user_id'], ['id'])
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key('campaigns_created_by_user_id_fkey', 'campaigns', 'users', ['created_by_user_id'], ['id'])
    op.drop_constraint(None, 'business_memberships', type_='foreignkey')
    op.drop_constraint(None, 'business_memberships', type_='foreignkey')
    op.create_foreign_key('business_memberships_business_id_fkey', 'business_memberships', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key('business_memberships_user_id_fkey', 'business_memberships', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'business_invitations', type_='foreignkey')
    op.drop_constraint(None, 'business_invitations', type_='foreignkey')
    op.create_foreign_key('business_invitations_invited_by_user_id_fkey', 'business_invitations', 'users', ['invited_by_user_id'], ['id'])
    op.create_foreign_key('business_invitations_redeemed_by_user_id_fkey', 'business_invitations', 'users', ['redeemed_by_user_id'], ['id'])
    # ### end Alembic commands ###
