"""Add user product tracking tables

Revision ID: c97a60f96378
Revises: 1d0c5abffcb5
Create Date: 2025-12-19 07:19:15.293014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97a60f96378'
down_revision: Union[str, None] = '1d0c5abffcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_product_scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('scan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_products_found', sa.Integer(), nullable=True),
    sa.Column('new_products_count', sa.Integer(), nullable=True),
    sa.Column('new_discounts_count', sa.Integer(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scan_date', name='uq_user_scan_date')
    )
    op.create_index('idx_scans_date', 'user_product_scans', ['scan_date'], unique=False)
    op.create_index('idx_scans_user_date', 'user_product_scans', ['user_id', 'scan_date'], unique=False)
    op.create_table('user_tracked_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'search_term', name='uq_user_tracked_product')
    )
    op.create_index('idx_tracked_products_active', 'user_tracked_products', ['is_active'], unique=False)
    op.create_index('idx_tracked_products_user', 'user_tracked_products', ['user_id'], unique=False)
    op.create_table('user_scan_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('tracked_product_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_title', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('discount_price', sa.Float(), nullable=True),
    sa.Column('was_discounted_yesterday', sa.Boolean(), nullable=True),
    sa.Column('is_new_today', sa.Boolean(), nullable=True),
    sa.Column('price_dropped_today', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['user_product_scans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tracked_product_id'], ['user_tracked_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scan_results_product', 'user_scan_results', ['product_id'], unique=False)
    op.create_index('idx_scan_results_scan', 'user_scan_results', ['scan_id'], unique=False)
    op.create_index('idx_scan_results_tracked', 'user_scan_results', ['tracked_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scan_results_tracked', table_name='user_scan_results')
    op.drop_index('idx_scan_results_scan', table_name='user_scan_results')
    op.drop_index('idx_scan_results_product', table_name='user_scan_results')
    op.drop_table('user_scan_results')
    op.drop_index('idx_tracked_products_user', table_name='user_tracked_products')
    op.drop_index('idx_tracked_products_active', table_name='user_tracked_products')
    op.drop_table('user_tracked_products')
    op.drop_index('idx_scans_user_date', table_name='user_product_scans')
    op.drop_index('idx_scans_date', table_name='user_product_scans')
    op.drop_table('user_product_scans')
    # ### end Alembic commands ###
