"""Add streak and daily bonus fields

Revision ID: c9a02c78436d
Revises: d0964ec3e4ec
Create Date: 2025-12-19 23:43:52.554822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a02c78436d'
down_revision: Union[str, None] = 'd0964ec3e4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server_default for existing rows
    op.add_column('user_daily_visits', sa.Column('daily_bonus_claimed', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('last_streak_milestone', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_streak_milestone')
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    op.drop_column('user_daily_visits', 'daily_bonus_claimed')
    # ### end Alembic commands ###
