"""Add exclusive coupons feature flags and coupon tables

Revision ID: ca6bf8085148
Revises: 2ab2cc41678f
Create Date: 2025-12-23 22:18:37.687948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6bf8085148'
down_revision: Union[str, None] = '2ab2cc41678f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('article_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normal_price', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Integer(), nullable=False),
    sa.Column('quantity_description', sa.String(length=100), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('remaining_quantity', sa.Integer(), nullable=False),
    sa.Column('credits_cost', sa.Integer(), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coupons_active', 'coupons', ['is_active'], unique=False)
    op.create_index('idx_coupons_business', 'coupons', ['business_id'], unique=False)
    op.create_table('user_coupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('redemption_code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_50_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_final_sent', sa.Boolean(), nullable=False),
    sa.Column('buyer_to_business_rating', sa.Integer(), nullable=True),
    sa.Column('buyer_to_business_comment', sa.Text(), nullable=True),
    sa.Column('buyer_product_review', sa.Text(), nullable=True),
    sa.Column('buyer_review_unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('buyer_review_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('business_to_buyer_rating', sa.Integer(), nullable=True),
    sa.Column('business_to_buyer_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_coupons_code', 'user_coupons', ['redemption_code'], unique=False)
    op.create_index('idx_user_coupons_coupon', 'user_coupons', ['coupon_id'], unique=False)
    op.create_index('idx_user_coupons_expires', 'user_coupons', ['expires_at'], unique=False)
    op.create_index('idx_user_coupons_status', 'user_coupons', ['status'], unique=False)
    op.create_index('idx_user_coupons_user', 'user_coupons', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_coupons_redemption_code'), 'user_coupons', ['redemption_code'], unique=False)
    op.add_column('businesses', sa.Column('business_type', sa.String(length=50), nullable=True))
    op.add_column('businesses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('address', sa.String(length=300), nullable=True))
    op.add_column('businesses', sa.Column('working_hours', sa.JSON(), nullable=True))
    op.add_column('businesses', sa.Column('has_exclusive_coupons', sa.Boolean(), nullable=True))
    op.add_column('businesses', sa.Column('max_coupons_allowed', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('businesses', sa.Column('total_reviews', sa.Integer(), nullable=True))

    # Set default values for existing businesses
    op.execute("UPDATE businesses SET business_type = 'supermarket' WHERE business_type IS NULL")
    op.execute("UPDATE businesses SET has_exclusive_coupons = false WHERE has_exclusive_coupons IS NULL")
    op.execute("UPDATE businesses SET max_coupons_allowed = 20 WHERE max_coupons_allowed IS NULL")
    op.execute("UPDATE businesses SET average_rating = 0 WHERE average_rating IS NULL")
    op.execute("UPDATE businesses SET total_reviews = 0 WHERE total_reviews IS NULL")

    # Insert default feature flag for exclusive coupons (disabled by default)
    op.execute("""
        INSERT INTO feature_flags (key, value, description, created_at, updated_at)
        VALUES ('exclusive_coupons_enabled', false, 'Omogućava sekciju Ekskluzivni Popusti na homepage i /ekskluzivni-popusti stranicu', NOW(), NOW())
        ON CONFLICT (key) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'total_reviews')
    op.drop_column('businesses', 'average_rating')
    op.drop_column('businesses', 'max_coupons_allowed')
    op.drop_column('businesses', 'has_exclusive_coupons')
    op.drop_column('businesses', 'working_hours')
    op.drop_column('businesses', 'address')
    op.drop_column('businesses', 'description')
    op.drop_column('businesses', 'business_type')
    op.drop_index(op.f('ix_user_coupons_redemption_code'), table_name='user_coupons')
    op.drop_index('idx_user_coupons_user', table_name='user_coupons')
    op.drop_index('idx_user_coupons_status', table_name='user_coupons')
    op.drop_index('idx_user_coupons_expires', table_name='user_coupons')
    op.drop_index('idx_user_coupons_coupon', table_name='user_coupons')
    op.drop_index('idx_user_coupons_code', table_name='user_coupons')
    op.drop_table('user_coupons')
    op.drop_index('idx_coupons_business', table_name='coupons')
    op.drop_index('idx_coupons_active', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
