"""Add verification_email_sent_at to users

Revision ID: d0964ec3e4ec
Revises: 371e2e8c9bfc
Create Date: 2025-12-19 21:26:45.667527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0964ec3e4ec'
down_revision: Union[str, None] = '371e2e8c9bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_email_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_email_sent_at')
    # ### end Alembic commands ###
