"""Add shopping list and favorites tables

Revision ID: e620e8e8e940
Revises: 
Create Date: 2025-11-12 16:49:05.018927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e620e8e8e940'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_credit_transactions_user_id', 'credit_transactions', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product_favorite')
    )
    op.create_index('idx_favorites_product_id', 'favorites', ['product_id'], unique=False)
    op.create_index('idx_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shopping_lists_expires_at', 'shopping_lists', ['expires_at'], unique=False)
    op.create_index('idx_shopping_lists_user_status', 'shopping_lists', ['user_id', 'status'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price_snapshot', sa.Float(), nullable=False),
    sa.Column('old_price_snapshot', sa.Float(), nullable=True),
    sa.Column('discount_percent_snapshot', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'product_id', 'business_id', name='uq_list_product_business')
    )
    op.create_index('idx_shopping_list_items_list_id', 'shopping_list_items', ['list_id'], unique=False)
    op.create_table('sms_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sms_outbox_created_at', 'sms_outbox', ['created_at'], unique=False)
    op.create_index('idx_sms_outbox_status', 'sms_outbox', ['status'], unique=False)
    # Add phone column to users table
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop phone column from users table
    op.drop_column('users', 'phone')
    # Drop SMS outbox table
    op.drop_index('idx_sms_outbox_status', table_name='sms_outbox')
    op.drop_index('idx_sms_outbox_created_at', table_name='sms_outbox')
    op.drop_table('sms_outbox')
    # Drop shopping list items table
    op.drop_index('idx_shopping_list_items_list_id', table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    # Drop shopping lists table
    op.drop_index('idx_shopping_lists_user_status', table_name='shopping_lists')
    op.drop_index('idx_shopping_lists_expires_at', table_name='shopping_lists')
    op.drop_table('shopping_lists')
    # Drop favorites table
    op.drop_index('idx_favorites_user_id', table_name='favorites')
    op.drop_index('idx_favorites_product_id', table_name='favorites')
    op.drop_table('favorites')
    # Drop credit transactions table
    op.drop_index('idx_credit_transactions_user_id', table_name='credit_transactions')
    op.drop_table('credit_transactions')
    # ### end Alembic commands ###
