"""Add stores table and coupon enhancements

Revision ID: e89fdecbf86f
Revises: ca6bf8085148
Create Date: 2025-12-23 23:35:59.436127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89fdecbf86f'
down_revision: Union[str, None] = 'ca6bf8085148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('google_maps_link', sa.String(), nullable=True),
    sa.Column('working_hours', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stores_active', 'stores', ['is_active'], unique=False)
    op.create_index('idx_stores_business', 'stores', ['business_id'], unique=False)
    op.create_index('idx_stores_city', 'stores', ['city'], unique=False)
    op.add_column('businesses', sa.Column('cover_image_path', sa.String(), nullable=True))
    op.add_column('coupons', sa.Column('store_id', sa.Integer(), nullable=True))
    op.add_column('coupons', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('coupons', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.create_index('idx_coupons_store', 'coupons', ['store_id'], unique=False)
    op.create_foreign_key(None, 'coupons', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupons', type_='foreignkey')
    op.drop_index('idx_coupons_store', table_name='coupons')
    op.drop_column('coupons', 'expires_at')
    op.drop_column('coupons', 'image_path')
    op.drop_column('coupons', 'store_id')
    op.drop_column('businesses', 'cover_image_path')
    op.drop_index('idx_stores_city', table_name='stores')
    op.drop_index('idx_stores_business', table_name='stores')
    op.drop_index('idx_stores_active', table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
