"""Add user_id and selected_stores to search_logs

Revision ID: edf83469ae72
Revises: a8f3c7d2e1b9
Create Date: 2026-01-02 20:10:39.199364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf83469ae72'
down_revision: Union[str, None] = 'a8f3c7d2e1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_logs', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('search_logs', sa.Column('selected_stores', sa.JSON(), nullable=True))
    op.create_index('idx_search_logs_user_id', 'search_logs', ['user_id'], unique=False)
    op.create_foreign_key('fk_search_logs_user_id', 'search_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_search_logs_user_id', 'search_logs', type_='foreignkey')
    op.drop_index('idx_search_logs_user_id', table_name='search_logs')
    op.drop_column('search_logs', 'selected_stores')
    op.drop_column('search_logs', 'user_id')
    # ### end Alembic commands ###
