"""Add monthly credits fields

Revision ID: f476c2810ecd
Revises: c9a02c78436d
Create Date: 2025-12-20 00:01:50.019978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f476c2810ecd'
down_revision: Union[str, None] = 'c9a02c78436d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add monthly credits columns with server defaults
    op.add_column('users', sa.Column('monthly_credits', sa.Integer(), nullable=True, server_default='40'))
    op.add_column('users', sa.Column('monthly_credits_used', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('monthly_credits_reset_date', sa.Date(), nullable=True))

    # Migrate existing weekly credits to monthly for existing users
    # Copy weekly_credits to monthly_credits for all existing users
    op.execute("""
        UPDATE users
        SET monthly_credits = COALESCE(weekly_credits, 40),
            monthly_credits_used = COALESCE(weekly_credits_used, 0),
            monthly_credits_reset_date = CURRENT_DATE
        WHERE monthly_credits IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_credits_reset_date')
    op.drop_column('users', 'monthly_credits_used')
    op.drop_column('users', 'monthly_credits')
    # ### end Alembic commands ###
